name: Generate GitHub Trophies

'on':
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: trophies.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
